### ISSUE TITLE
Gradio port is set to 7860 instead of 3001

### ISSUE THREAD

**Issue by NicholasDreyer** [ashleykleynhans/tts-generation-docker#1]
I just installed version 2.4.0 and was not able to access the web UI from 3000. Changing the container's port to 7860 resolved the issue. My working docker run command:

docker run -d \
  --gpus all \
  -v /workspace \
  -p 3000:7860 \
  -p 8888:8888 \
  -p 2999:2999 \
  -e VENV_PATH="/workspace/venvs/tts-generation-webui" \
  ashleykza/tts-generation:latest

**Comment by ashleykleynhans** [comment]
Port 3000 is not gradio, it is the nginx reverse proxy server.
https://github.com/ashleykleynhans/tts-generation-docker/blob/main/nginx/nginx.conf#L26
