### ISSUE TITLE
error trying to build the docker image

### ISSUE THREAD

**Issue by mediashock** [ashleykleynhans/tts-generation-docker#2]
Hey, I'm trying to run this docker image but getting the following error, any idea why?

` => ERROR [3/9] RUN /install.sh && rm /install.sh                                                            0.3s
------
 > [3/9] RUN /install.sh && rm /install.sh:
0.257 /usr/bin/env: 'bash\r': No such file or directory
------
Dockerfile:20
--------------------
  18 |     ENV TTS_COMMIT=${TTS_COMMIT}
  19 |     COPY --chmod=755 build/install.sh /install.sh
  20 | >>> RUN /install.sh && rm /install.sh
  21 |
  22 |     # Copy configuration files
--------------------
ERROR: failed to solve: process "/bin/bash -o pipefail -c /install.sh && rm /install.sh" did not complete successfully: exit code: 127`

**Comment by ashleykleynhans** [comment]
Seems like a Windows issue, don't edit the files on Windows.  This builds fine on Linux, I don't support Windows.
