### ISSUE TITLE
Install failed...any clues?

### ISSUE THREAD

**Issue by kommanderinkief** [ashleykleynhans/tts-generation-docker#3]
$ docker buildx bake -f docker-bake.hcl --push
#0 building with "default" instance using docker driver

#1 [internal] load .dockerignore
#1 transferring context: 2B 0.0s done
#1 DONE 0.1s

#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 1.03kB 0.0s done
#2 DONE 0.1s

#3 [internal] load metadata for docker.io/ashleykza/runpod-base:2.0.0-python3.10-cuda12.1.1-torch2.3.1
#3 ...

#4 [auth] ashleykza/runpod-base:pull token for registry-1.docker.io
#4 DONE 0.0s

#3 [internal] load metadata for docker.io/ashleykza/runpod-base:2.0.0-python3.10-cuda12.1.1-torch2.3.1
#3 DONE 0.4s

#5 [1/9] FROM docker.io/ashleykza/runpod-base:2.0.0-python3.10-cuda12.1.1-torch2.3.1@sha256:9a099b9eadbcb91e9811446fb37dd8661964a358fcedf4689c3960374491d9cc
#5 DONE 0.0s

#6 [internal] load build context
#6 transferring context: 292B 0.0s done
#6 DONE 0.1s

#7 [2/9] COPY --chmod=755 build/install.sh /install.sh
#7 CACHED

#8 [3/9] RUN /install.sh && rm /install.sh
#8 0.380 /usr/bin/env: 'bash\r': No such file or directory
#8 ERROR: process "/bin/bash -o pipefail -c /install.sh && rm /install.sh" did not complete successfully: exit code: 127
------
 > [3/9] RUN /install.sh && rm /install.sh:
0.380 /usr/bin/env: 'bash\r': No such file or directory
------
Dockerfile:20
--------------------
  18 |     ENV TTS_COMMIT=${TTS_COMMIT}
  19 |     COPY --chmod=755 build/install.sh /install.sh
  20 | >>> RUN /install.sh && rm /install.sh
  21 |
  22 |     # Copy configuration files
--------------------
ERROR: failed to solve: process "/bin/bash -o pipefail -c /install.sh && rm /install.sh" did not complete successfully: exit code: 127

**Comment by ashleykleynhans** [comment]
Use my docker image, I can't help you build it, it works for me.
